#!/usr/bin/env php
<?php

if ( ! isset($argv[1])) {
    throw new \InvalidArgumentException('You must specify the name of your project.');
}

$projectName = $argv[1];

exec('cp -R ' . __DIR__ . '/* .');
exec(sprintf("find ./* -type f | xargs perl -pi -e 's/SkeletonProject/%s/g'", $projectName));
exec('rm copy');
exec(sprintf('mv lib/SkeletonProject lib/%s', $projectName));
exec(sprintf('mv tests/SkeletonProject/Tests/SkeletonProject tests/SkeletonProject/Tests/%s', $projectName));
exec(sprintf('mv tests/SkeletonProject tests/%s', $projectName));